ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of EWdim6'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_91 = ', GC_91
      WRITE(*,2) 'GC_94 = ', GC_94
      WRITE(*,2) 'GC_121 = ', GC_121
      WRITE(*,2) 'GC_145 = ', GC_145
