ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=3D0)
      DOUBLE PRECISION NL
      PARAMETER(NL=1D0)

      DOUBLE PRECISION MDL_MB,MDL_MC,MDL_MH,MDL_MM,MDL_MP,MDL_MT
     $ ,MDL_MTA,MDL_MW,MDL_MZ

      COMMON/MASSES/ MDL_MB,MDL_MC,MDL_MH,MDL_MM,MDL_MP,MDL_MT,MDL_MTA
     $ ,MDL_MW,MDL_MZ


      DOUBLE PRECISION MDL_WH,MDL_WH1,MDL_WT,MDL_WTAU,MDL_WW,MDL_WZ

      COMMON/WIDTHS/ MDL_WH,MDL_WH1,MDL_WT,MDL_WTAU,MDL_WW,MDL_WZ


      DOUBLE COMPLEX GC_1, GC_62, GC_91, GC_92, GC_93, GC_94, GC_117,
     $  GC_145

      COMMON/COUPLINGS/ GC_1, GC_62, GC_91, GC_92, GC_93, GC_94,
     $  GC_117, GC_145

