#!/bin/bash

# Script generated by MadMiner

# Usage: run_0.sh MG_directory MG_process_directory log_dir

export PATH=/usr/bin:$PATH 

mgdir=$1
mgprocdir=$2
mmlogdir=$3

cp $mgprocdir/madminer/cards/run_card_0.dat $mgprocdir/Cards/run_card.dat
cp $mgprocdir/madminer/cards/param_card_0.dat $mgprocdir/Cards/param_card.dat
cp $mgprocdir/madminer/cards/reweight_card_0.dat $mgprocdir/Cards/reweight_card.dat

sed -e 's@\$mgprocdir@'"$mgprocdir"'@' $mgprocdir/madminer/cards/mg_commands_0.dat > $mgprocdir/Cards/mg_commands.mg5

python3  $mgdir/bin/mg5_aMC $mgprocdir/Cards/mg_commands.mg5 > $mmlogdir/run_0.log
