C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Epsilon(1,2,-1,-2)*P(-2,1)*P(-1,3) -
C      Epsilon(1,2,-1,-2)*P(-2,2)*P(-1,3)
C     
      SUBROUTINE VVS2P1N_3(V1, V2, COUP,S3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      COMPLEX*16 S3(3)
      COMPLEX*16 TMP1
      COMPLEX*16 TMP2
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      P1(0) = DBLE(V1(1))
      P1(1) = DBLE(V1(2))
      P1(2) = DIMAG(V1(2))
      P1(3) = DIMAG(V1(1))
      P2(0) = DBLE(V2(1))
      P2(1) = DBLE(V2(2))
      P2(2) = DIMAG(V2(2))
      P2(3) = DIMAG(V2(1))
      S3(1) = +V1(1)+V2(1)
      S3(2) = +V1(2)+V2(2)
      P3(0) = -DBLE(S3(1))
      P3(1) = -DBLE(S3(2))
      P3(2) = -DIMAG(S3(2))
      P3(3) = -DIMAG(S3(1))
      TMP1 = (-1D0)*(P1(0)*(P3(1)*(V2(6)*V1(5)-V2(5)*V1(6))+(P3(2)*(
     $ -V2(6)*V1(4)+V2(4)*V1(6))+P3(3)*(V2(5)*V1(4)-V2(4)*V1(5))))
     $ +(P1(1)*(P3(0)*(-V2(6)*V1(5)+V2(5)*V1(6))+(P3(2)*(V2(6)*V1(3)
     $ -V2(3)*V1(6))+P3(3)*(-V2(5)*V1(3)+V2(3)*V1(5))))+(P1(2)*(P3(0)
     $ *(V2(6)*V1(4)-V2(4)*V1(6))+(P3(1)*(-V2(6)*V1(3)+V2(3)*V1(6))
     $ +P3(3)*(V2(4)*V1(3)-V2(3)*V1(4))))+P1(3)*(P3(0)*(-V2(5)*V1(4)
     $ +V2(4)*V1(5))+(P3(1)*(V2(5)*V1(3)-V2(3)*V1(5))+P3(2)*(-V2(4)
     $ *V1(3)+V2(3)*V1(4)))))))
      TMP2 = (-1D0)*(P2(0)*(P3(1)*(V2(6)*V1(5)-V2(5)*V1(6))+(P3(2)*(
     $ -V2(6)*V1(4)+V2(4)*V1(6))+P3(3)*(V2(5)*V1(4)-V2(4)*V1(5))))
     $ +(P2(1)*(P3(0)*(-V2(6)*V1(5)+V2(5)*V1(6))+(P3(2)*(V2(6)*V1(3)
     $ -V2(3)*V1(6))+P3(3)*(-V2(5)*V1(3)+V2(3)*V1(5))))+(P2(2)*(P3(0)
     $ *(V2(6)*V1(4)-V2(4)*V1(6))+(P3(1)*(-V2(6)*V1(3)+V2(3)*V1(6))
     $ +P3(3)*(V2(4)*V1(3)-V2(3)*V1(4))))+P2(3)*(P3(0)*(-V2(5)*V1(4)
     $ +V2(4)*V1(5))+(P3(1)*(V2(5)*V1(3)-V2(3)*V1(5))+P3(2)*(-V2(4)
     $ *V1(3)+V2(3)*V1(4)))))))
      S3(3)= COUP*(-CI*(TMP1)+CI*(TMP2))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Epsilon(1,2,-1,-2)*P(-2,1)*P(-1,3) -
C      Epsilon(1,2,-1,-2)*P(-2,2)*P(-1,3)
C     
      SUBROUTINE VVS2_4_6P1N_3(V1, V2, COUP1, COUP2, COUP3,S3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      COMPLEX*16 S3(3)
      COMPLEX*16 STMP(3)
      COMPLEX*16 V1(*)
      COMPLEX*16 V2(*)
      INTEGER*4 I
      CALL VVS2P1N_3(V1,V2,COUP1,S3)
      CALL VVS4P1N_3(V1,V2,COUP2,STMP)
      DO I = 3, 3
        S3(I) = S3(I) + STMP(I)
      ENDDO
      CALL VVS6P1N_3(V1,V2,COUP3,STMP)
      DO I = 3, 3
        S3(I) = S3(I) + STMP(I)
      ENDDO
      END


